### ISSUE TITLE
buidler test are failing

### ISSUE THREAD

**Issue by vlddm** [Austin-Williams/uniswap-flash-swapper#12]
```
user@lap:~ $ yarn run test
yarn run v1.22.4
$ buidler test
All contracts have already been compiled, skipping compilation.


  Example

Setting up signer...
  signer: 0x1F3dF0b8390BB8e9e322972C5e75583E87608Ec2

Deploying example contract...
  example contract: 0x8FE5b83592aE9468734ebcc1F9a190c37d004AD3

Testing swap - borrows 1 ETH, paying with ETH

Ensuring that contract can cover fees...
  contract ETH balance 0
  contract will not be able to cover fee, sending from signer...
  signer ETH balance 90128633065843325448
  new contract ETH balance 0

Performing flash swap...
    1) successfully flash swaps


  0 passing (8s)
  1 failing

  1) Example
       successfully flash swaps:
     Error: VM Exception while processing transaction: revert
      at HttpProvider.send (node_modules/@nomiclabs/buidler/src/internal/core/providers/http.ts:36:34)
      at /Users/user/code/uniswap-flash-swapper/node_modules/@nomiclabs/buidler/src/internal/core/providers/accounts.ts:219:21
      at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
      at /Users/user/code/uniswap-flash-swapper/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:23:21
      at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
      at /Users/user/code/uniswap-flash-swapper/node_modules/@nomiclabs/buidler/src/internal/core/providers/gas-providers.ts:41:21
      at Proxy.cloningSendWrapper (node_modules/@nomiclabs/buidler/src/internal/core/providers/wrapper.ts:9:12)
      at EthersProviderWrapper.send (node_modules/@nomiclabs/buidler-ethers/src/ethers-provider-wrapper.ts:13:48)
      at /Users/user/code/uniswap-flash-swapper/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:164:35
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by travelerr** [comment]
@vlddm did you ever find a solution to this? I'm running into the same thing

**Comment by Miyou** [comment]
Looks like the arguments to factory.deploy are in the wrong order in [Example.test.ts](https://github.com/Austin-Williams/uniswap-flash-swapper/blob/master/test/Example.test.ts#L54).
Switch to this and it works:
```
exampleContract = await factory.deploy(
  addresses.getTokenAddress('DAI'),
  addresses.getTokenAddress('WETH'),
  OVERRIDES
);
```

**Comment by scglenn** [comment]
This change worked. I'll make a pull request if there isn't one.
